platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BABCropperView'do
  pod "BABCropperView", :path => "../"
end

target 'Tests' do
  pod "BABCropperView", :path => "../"

  
end
